### ISSUE TITLE
Train error 'KeyError: 'MASTER is not in the models registry''

### ISSUE THREAD

**Issue by ThorPham** [JiaquanYe/MASTER-mmocr#5]
work_dir = 'weights'
gpu_ids = range(0, 1)

Traceback (most recent call last):
  File "tools/train.py", line 221, in <module>
    main()
  File "tools/train.py", line 185, in main
    test_cfg=cfg.get('test_cfg'))
  File "/home/thorpham/Documents/challenge/mmocr/mmocr/models/builder.py", line 140, in build_detector
    cfg, default_args=dict(train_cfg=train_cfg, test_cfg=test_cfg))
  File "/home/thorpham/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/utils/registry.py", line 212, in build
    return self.build_func(*args, **kwargs, registry=self)
  File "/home/thorpham/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/cnn/builder.py", line 27, in build_model_from_cfg
    return build_from_cfg(cfg, registry, default_args)
  File "/home/thorpham/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/utils/registry.py", line 45, in build_from_cfg
    f'{obj_type} is not in the {registry.name} registry')
KeyError: 'MASTER is not in the models registry'

Can you help me fix error ? Thank you

**Comment by ThorPham** [comment]
@JiaquanYe do you modify code  in mmdetection-2.11.0 . Which code you modify .I use mmocr-0.4 so it must  mmdet-2.18.1

**Comment by JiaquanYe** [comment]
> @JiaquanYe do you modify code in mmdetection-2.11.0 . Which code you modify .I use mmocr-0.4 so it must mmdet-2.18.1

Yes, I have modify the mmocr and mmdetection source code. You should install mmocr and mmdetection-2.11.0 in this repo. 
The installation details can be found in README.
